defaultElo: 1200
arenaCountDownTime: 10 #10 seconds

messages:
  arenaCountDown: "&eStarting in {time}&ls&e..."
  duelStart: "&eDuel Started"
  setSpawnPoint: "&eSet spawn point to {location}."
  reloadConfig: "&eReloaded config."
  startingSetUp: "&eStarting the setup."
  positionNotSet: "&cError: Position {position} is not set."
  createArena: "&eYou've created the arena!"
  playerDoesNotExist: "&cThe player {name} doesn't exists."
  setPosition: "&eSet position-{number} to &7({location})"
  consoleHasNoStats: "&cConsole has no stats."
  playerLeaveGame: "&c{player} left the game."
  duelEnd: "&cThe duel has ended!"
  errorNoPermission: "&cYou don't have the permission {permission}"
  rankedDuelWinnerMessages:
  - "&8&m---------------------------------"
  - "&e{winner} has won the duel"
  - "&e{winner} had {winner_health} health left"
  - "&e{loser} had {loser_health} health left"
  - "&e{loser} &c{elo_loss}"
  - "&e{winner} &c{elo_gain}"
  - "&8&m---------------------------------"
  unRankedDuelWinnerMessages:
  - "&8&m---------------------------------"
  - "&e{winner} has won the duel"
  - "&e{winner} had {winner_health} health left"
  - "&e{loser} had {loser_health} health left"
  - "&8&m---------------------------------"
  playerStats:
  - "&8&m---------------------------------"
  - "&eUsername: &b{name}"
  - "&e&lElo"
  - "  &eRefill: &b{refill_elo}"
  - "  &eNo Refill: &b{no_refill_elo}"
  - "&e&lDeaths"
  - "  &eRefill: &b{refill_deaths}"
  - "  &eNo Refill: &b{no_refill_deaths}"
  - "&e&lKills"
  - "  &eRefill: &b{refill_kills}"
  - "  &eNo Refill: &b{no_refill_kills}"
  - "&eCredits: &b{credits}"
  - "&eTotal Kills: &b{total_kills}"
  - "&eTotal Deaths: &b{total_deaths}"
  - "&eTotal KDR: &b{total_kdr}"
  - "&eGlobal Elo: &b{global_elo}"
  - "&eRanked Wins: &b{ranked_wins}"
  - "&eUnranked Wins: &b{unranked_wins}"
  - "&8&m---------------------------------"

permissions:
  setSpawn: "duels.setSpawn"
  reloadDuels: "duels.reload"
  setArenaSpawnPoint: "duels.addArenaSpawnPoint"
  setupArena: "duels.setup"


joinMessageList:
- " "
- " "
- " "
- " "
- " "
- " "
- " "
- " "
- " "
- " "
- "&c============================================="
- "&fWelcome &b{player} &fto &b&lDuels&f&lMc"
- " "
- "  &7Type &n/duel <playerName> &7 to duel a player"
- "&c============================================="
- " "

spawnScoreboardTitle: "&b&lMc&f&lKits Duels"
spawnScoreboardLines:
- " "
- "&bIGN: &f{ign}"
- "&bOnline Staff: &f{online_staff_size}"
- "&bElo: &f{global_elo}"
- "&bCredits: &f{credits}"
- " "
- "&bserver_ip_here"

queueItemName: "&a&l{ladder} &7(Click)"
queueItemLore:
- "&eIn Queue: &a{in_queue_amount}"
- "&eIn Game: &a{in_game_amount}"
