name: McKitsDuels
version: ${project.version}
main: me.matt11matthew.mckit.McKitsDuels
authors: [matt11matthew]
commands:
  duel:
  setspawn:
  stats:
  rankedmenu:
  unrankedmenu:
  elotop:
  setuparena:
  duelsreload:
  confirmcreation:
  dev:
  setarenaspawnpoint:
